server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.164.140
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: localhost
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
